networks:
  services-network:
    external: true
    name: ${NETWORK_NAME:-services-network}

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./../../data/portainer/

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:${IMAGE_VERSION:-lts}
    restart: always
    networks:
      - services-network
    expose:
      - 9000
    ports:
      - 9000:9000
    env_file: .env
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
