networks:
  services-network:
    external: true
    name: ${NETWORK_NAME:-services-network}

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./../../data/traefik/

services:
  traefik:
    container_name: traefik
    image: traefik:${IMAGE_VERSION:-beaufort}
    restart: always
    healthcheck:
      test:
        - CMD-SHELL
        - wget -q --spider --proxy off localhost:8080/ping || exit 1
      interval: 10s
      retries: 3
    networks:
      - services-network
    expose:
      - 8080 # traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - data/certs:/certs
    env_file: .env
    command:
      - --serverstransport.insecureskipverify=${INSECURE_SERVER:-true}
      - --api=true
      - --api.dashboard=true
      - --api.insecure=true
      - --ping=true
      - --metrics.prometheus=true
      - --metrics.prometheus.addEntryPointsLabels=true
      - --metrics.prometheus.addrouterslabels=true
      - --metrics.prometheus.addServicesLabels=true
      - --global.sendanonymoususage=false
      - --global.checknewversion=false
      - --log.level=${LOG_LEVEL:-INFO}
      - --accesslog=true
      - --providers.docker=${TRAEFIK_DOCKER:-true}
      - --providers.docker.network=${NETWORK_NAME:-services-network}
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.docker.watch=true
      - --providers.swarm=${TRAEFIK_SWARM:-false}
      - --providers.swarm.exposedbydefault=false
      - --providers.swarm.network=${NETWORK_NAME:-services-network}
      - --entrypoints.http.address=:${HTTP_PORT:-80}
      - --entrypoints.https.address=:${HTTPS_PORT:-443}
      - --entrypoints.socks.address=:${SOCKS_PORT:-1080}
      - --entrypoints.ftp-data.address=:${FTP_DATA_PORT:-20}
      - --entrypoints.ftp.address=:${FTP_PORT:-21}
      - --entrypoints.ftps-data.address=:${FTPS_DATA_PORT:-989}
      - --entrypoints.ftps.address=:${FTPS_PORT:-990}
      - --entrypoints.smb1.address=:${SMB1_PORT:-139}
      - --entrypoints.smb.address=:${SMB_PORT:-445}
      - --entrypoints.rsync.address=:${RSYNC_PORT:-873}
      - --entrypoints.nfs.address=:${NFS_PORT:-2049}
      - --entrypoints.svn.address=:${SVN_PORT:-3690}
      - --entrypoints.ssh.address=:${SSH_PORT:-22}
      - --entrypoints.telnet.address=:${TELNET_PORT:-23}
      - --entrypoints.telnets.address=:${TELNETS_PORT:-992}
      - --entrypoints.rdp.address=:${RDP_PORT:-3389}
      - --entrypoints.vnc.address=:${VNC_PORT:-5900}
      - --entrypoints.x11.address=:${X11_PORT:-6000}
      - --entrypoints.smtp-legacy.address=:${SMTP_LEGACY_PORT:-25}
      - --entrypoints.smtp.address=:${SMTP_PORT:-587}
      - --entrypoints.smtps.address=:${SMTPS_PORT:-465}
      - --entrypoints.imap.address=:${IMAP_PORT:-143}
      - --entrypoints.imaps.address=:${IMAPS_PORT:-993}
      - --entrypoints.pop3.address=:${POP3_PORT:-110}
      - --entrypoints.pop3s.address=:${POP3S_PORT:-995}
      - --entrypoints.dns.address=:${DNS_PORT:-53}
      - --entrypoints.dot.address=:${DOT_PORT:-853}
      - --entrypoints.ldap.address=:${LDAP_PORT:-389}
      - --entrypoints.ldaps.address=:${LDAPS_PORT:-636}
      - --entrypoints.mssql.address=:${MSSQL_PORT:-1433}
      - --entrypoints.mssqlm.address=:${MSSQLM_PORT:-1434}
      - --entrypoints.mysql.address=:${MYSQL_PORT:-3306}
      - --entrypoints.postgres.address=:${POSTGRES_PORT:-5432}
      - --entrypoints.couchdb.address=:${COUCHDB_PORT:-5984}
      - --entrypoints.redis.address=:${REDIS_PORT:-6379}
      - --entrypoints.clickhouse.address=:${CLICKHOUSE_PORT:-9000}
      - --entrypoints.mongodb.address=:${MONGODB_PORT:-27017}
      - --entrypoints.l2tp.address=:${L2TP_PORT:-1701}
      - --entrypoints.docker.address=:${DOCKER_PORT:-2375}
      - --entrypoints.dockers.address=:${DOCKERS_PORT:-2376}
      - --entrypoints.docker-swarm.address=:${DOCKER_SWARM_PORT:-2377}
      - --entrypoints.k8s.address=:${K8S_PORT:-6443}
      - --certificatesresolvers.le.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.le.acme.storage=/certs/acme.json
      - --certificatesresolvers.le.acme.dnschallenge.provider=${DNS_RPOVIDER:-cloudflare}
      - --certificatesresolvers.le.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53
      - --certificatesresolvers.le.acme.dnschallenge.delaybeforecheck=30
      - --experimental.plugins.coraza.modulename=github.com/jcchavezs/coraza-http-wasm-traefik
      - --experimental.plugins.coraza.version=v0.2.2
      - --experimental.plugins.fail2ban.modulename=github.com/tomMoulard/fail2ban
      - --experimental.plugins.fail2ban.version=v0.8.1
      - --experimental.plugins.geoblock.modulename=github.com/PascalMinder/geoblock
      - --experimental.plugins.geoblock.version=v0.2.8
      - --experimental.plugins.ldapAuth.modulename=github.com/wiltonsr/ldapAuth
      - --experimental.plugins.ldapAuth.version=v0.1.8
      - --experimental.plugins.real-ip.modulename=github.com/Paxxs/traefik-get-real-ip
      - --experimental.plugins.real-ip.version=v1.0.2
      - --experimental.plugins.trauth.modulename=github.com/leonjza/trauth
      - --experimental.plugins.trauth.version=v1.6.0
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
