services:
  traefik:
    ports:
    - published: ${HTTP_PORT:-80}
      target: ${HTTP_PORT:-80}
      protocol: tcp
      mode: ${PORT_MODE:-host}
    - published: ${HTTP_PORT:-80}
      target: ${HTTP_PORT:-80}
      protocol: udp
      mode: ${PORT_MODE:-host}
    - published: ${HTTPS_PORT:-443}
      target: ${HTTPS_PORT:-443}
      protocol: tcp
      mode: ${PORT_MODE:-host}
    - published: ${HTTPS_PORT:-443}
      target: ${HTTPS_PORT:-443}
      protocol: udp
      mode: ${PORT_MODE:-host}
    - published: ${SSH_PORT:-22}
      target: ${SSH_PORT:-22}
      protocol: tcp
      mode: ${PORT_MODE:-host}
    - published: ${SMTP_LEGACY_PORT:-25}
      target: ${SMTP_LEGACY_PORT:-25}
      protocol: tcp
      mode: ${PORT_MODE:-host}
    - published: ${SMTP_PORT:-587}
      target: ${SMTP_PORT:-587}
      protocol: tcp
      mode: ${PORT_MODE:-host}
    - published: ${SMTPS_PORT:-465}
      target: ${SMTPS_PORT:-465}
      protocol: tcp
      mode: ${PORT_MODE:-host}
    - published: ${IMAP_PORT:-143}
      target: ${IMAP_PORT:-143}
      protocol: tcp
      mode: ${PORT_MODE:-host}
    - published: ${IMAPS_PORT:-993}
      target: ${IMAPS_PORT:-993}
      protocol: tcp
      mode: ${PORT_MODE:-host}
    - published: ${POP3_PORT:-110}
      target: ${POP3_PORT:-110}
      protocol: tcp
      mode: ${PORT_MODE:-host}
    - published: ${POP3S_PORT:-995}
      target: ${POP3S_PORT:-995}
      protocol: tcp
      mode: ${PORT_MODE:-host}
    - published: ${LDAP_PORT:-389}
      target: ${LDAP_PORT:-389}
      protocol: tcp
      mode: ${PORT_MODE:-host}
    - published: ${LDAPS_PORT:-636}
      target: ${LDAPS_PORT:-636}
      protocol: tcp
      mode: ${PORT_MODE:-host}
    - published: ${RDP_PORT:-3389}
      target: ${RDP_PORT:-3389}
      protocol: tcp
      mode: ${PORT_MODE:-host}
    - published: ${VNC_PORT:-5900}
      target: ${VNC_PORT:-5900}
      protocol: tcp
      mode: ${PORT_MODE:-host}
    - published: ${MSSQL_PORT:-1433}
      target: ${MSSQL_PORT:-1433}
      protocol: tcp
      mode: ${PORT_MODE:-host}
    - published: ${MSSQLM_PORT:-1434}
      target: ${MSSQLM_PORT:-1434}
      protocol: tcp
      mode: ${PORT_MODE:-host}
    - published: ${MYSQL_PORT:-3306}
      target: ${MYSQL_PORT:-3306}
      protocol: tcp
      mode: ${PORT_MODE:-host}
    - published: ${POSTGRES_PORT:-5432}
      target: ${POSTGRES_PORT:-5432}
      protocol: tcp
      mode: ${PORT_MODE:-host}
    - published: ${COUCHDB_PORT:-5984}
      target: ${COUCHDB_PORT:-5984}
      protocol: tcp
      mode: ${PORT_MODE:-host}
    - published: ${REDIS_PORT:-6379}
      target: ${REDIS_PORT:-6379}
      protocol: tcp
      mode: ${PORT_MODE:-host}
    - published: ${CLICKHOUSE_PORT:-9000}
      target: ${CLICKHOUSE_PORT:-9000}
      protocol: tcp
      mode: ${PORT_MODE:-host}
    - published: ${MONGODB_PORT:-27017}
      target: ${MONGODB_PORT:-27017}
      protocol: tcp
      mode: ${PORT_MODE:-host}
